#!/usr/bin/env python3
"""
Generate a new resource with model, schema, router, and frontend pages.
Usage: python scripts/generate_resource.py ResourceName

This creates:
- backend/app/models/{resource_name}.py
- backend/app/schemas/{resource_name}.py
- backend/app/routers/{resource_name}s.py
- frontend/src/pages/{ResourceName}List.tsx
- frontend/src/pages/{ResourceName}Detail.tsx
- frontend/src/pages/{ResourceName}Form.tsx
"""
import sys
import os
from pathlib import Path


def to_snake_case(name):
    """Convert CamelCase to snake_case."""
    import re
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def generate_model(resource_name, snake_name):
    """Generate SQLAlchemy model."""
    return f'''"""
{resource_name} model.
Generated by scripts/generate_resource.py
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from app.core.database import Base
from app.core.config import settings


class {resource_name}(Base):
    __tablename__ = "{snake_name}s"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True, nullable=False)
    description = Column(Text, nullable=True)
    owner_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Optional: Multi-tenant field
    tenant_id = Column(Integer, ForeignKey("tenants.id"), nullable=True) if settings.ENABLE_TENANCY else None

    # Relationships
    owner = relationship("User")

    def __repr__(self):
        return f"<{resource_name} {{self.title}}>"
'''


def generate_schema(resource_name):
    """Generate Pydantic schemas."""
    return f'''"""
{resource_name} schemas for validation.
Generated by scripts/generate_resource.py
"""
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field


class {resource_name}Base(BaseModel):
    title: str = Field(..., min_length=1, max_length=200)
    description: Optional[str] = None


class {resource_name}Create({resource_name}Base):
    pass


class {resource_name}Update(BaseModel):
    title: Optional[str] = Field(None, min_length=1, max_length=200)
    description: Optional[str] = None


class {resource_name}({resource_name}Base):
    id: int
    owner_id: int
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True
'''


def generate_router(resource_name, snake_name):
    """Generate FastAPI router."""
    plural = f"{snake_name}s"
    return f'''"""
{resource_name} CRUD endpoints.
Generated by scripts/generate_resource.py
"""
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.core.security import get_current_active_user
from app.core.config import settings
from app.models.user import User
from app.models.{snake_name} import {resource_name}
from app.schemas.{snake_name} import {resource_name} as {resource_name}Schema, {resource_name}Create, {resource_name}Update

router = APIRouter(prefix="/{plural}", tags=["{plural}"])


def apply_tenant_filter(query, user: User):
    """Apply tenant filter if multi-tenancy is enabled."""
    if settings.ENABLE_TENANCY and hasattr(user, "tenant_id"):
        query = query.filter({resource_name}.tenant_id == user.tenant_id)
    return query


@router.get("", response_model=List[{resource_name}Schema])
def list_{plural}(
    skip: int = 0,
    limit: int = 100,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """List all {plural}."""
    query = db.query({resource_name})
    query = apply_tenant_filter(query, current_user)
    {plural} = query.offset(skip).limit(limit).all()
    return {plural}


@router.post("", response_model={resource_name}Schema, status_code=status.HTTP_201_CREATED)
def create_{snake_name}(
    {snake_name}_in: {resource_name}Create,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """Create a new {snake_name}."""
    {snake_name}_data = {snake_name}_in.model_dump()
    {snake_name}_data["owner_id"] = current_user.id

    if settings.ENABLE_TENANCY and hasattr(current_user, "tenant_id"):
        {snake_name}_data["tenant_id"] = current_user.tenant_id

    db_{snake_name} = {resource_name}(**{snake_name}_data)
    db.add(db_{snake_name})
    db.commit()
    db.refresh(db_{snake_name})
    return db_{snake_name}


@router.get("/{{{snake_name}_id}}", response_model={resource_name}Schema)
def get_{snake_name}(
    {snake_name}_id: int,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """Get {snake_name} by ID."""
    query = db.query({resource_name}).filter({resource_name}.id == {snake_name}_id)
    query = apply_tenant_filter(query, current_user)
    {snake_name} = query.first()

    if not {snake_name}:
        raise HTTPException(status_code=404, detail="{resource_name} not found")
    return {snake_name}


@router.put("/{{{snake_name}_id}}", response_model={resource_name}Schema)
def update_{snake_name}(
    {snake_name}_id: int,
    {snake_name}_update: {resource_name}Update,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """Update a {snake_name}."""
    query = db.query({resource_name}).filter({resource_name}.id == {snake_name}_id)
    query = apply_tenant_filter(query, current_user)
    {snake_name} = query.first()

    if not {snake_name}:
        raise HTTPException(status_code=404, detail="{resource_name} not found")

    if {snake_name}.owner_id != current_user.id and current_user.role != "admin":
        raise HTTPException(status_code=403, detail="Not enough permissions")

    update_data = {snake_name}_update.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        setattr({snake_name}, field, value)

    db.commit()
    db.refresh({snake_name})
    return {snake_name}


@router.delete("/{{{snake_name}_id}}", status_code=status.HTTP_204_NO_CONTENT)
def delete_{snake_name}(
    {snake_name}_id: int,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """Delete a {snake_name}."""
    query = db.query({resource_name}).filter({resource_name}.id == {snake_name}_id)
    query = apply_tenant_filter(query, current_user)
    {snake_name} = query.first()

    if not {snake_name}:
        raise HTTPException(status_code=404, detail="{resource_name} not found")

    if {snake_name}.owner_id != current_user.id and current_user.role != "admin":
        raise HTTPException(status_code=403, detail="Not enough permissions")

    db.delete({snake_name})
    db.commit()
    return None
'''


def generate_frontend_list(resource_name):
    """Generate React list page."""
    plural = f"{resource_name}s"
    return f'''import {{ useState, useEffect }} from 'react';
import {{ Link }} from 'react-router-dom';
import {{ api }} from '../lib/api';

export default function {resource_name}List() {{
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {{
    loadItems();
  }}, []);

  const loadItems = async () => {{
    try {{
      const data = await api.get('/{to_snake_case(resource_name)}s');
      setItems(data);
    }} catch (error) {{
      console.error('Failed to load {plural.lower()}:', error);
    }} finally {{
      setLoading(false);
    }}
  }};

  const handleDelete = async (id: number) => {{
    if (!confirm('Are you sure?')) return;
    try {{
      await api.delete(`/{to_snake_case(resource_name)}s/${{id}}`);
      loadItems();
    }} catch (error) {{
      console.error('Failed to delete:', error);
    }}
  }};

  if (loading) return <div className="p-8">Loading...</div>;

  return (
    <div className="max-w-6xl mx-auto p-8">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold">{plural}</h1>
        <Link
          to="/{to_snake_case(resource_name)}s/new"
          className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700"
        >
          Create {resource_name}
        </Link>
      </div>

      <div className="bg-white shadow rounded-lg overflow-hidden">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                Title
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                Description
              </th>
              <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">
                Actions
              </th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {{items.map((item: any) => (
              <tr key={{item.id}}>
                <td className="px-6 py-4">
                  <Link to={{`/{to_snake_case(resource_name)}s/${{item.id}}`}} className="text-blue-600 hover:underline">
                    {{item.title}}
                  </Link>
                </td>
                <td className="px-6 py-4 text-gray-600">{{item.description}}</td>
                <td className="px-6 py-4 text-right space-x-2">
                  <Link
                    to={{`/{to_snake_case(resource_name)}s/${{item.id}}/edit`}}
                    className="text-indigo-600 hover:underline"
                  >
                    Edit
                  </Link>
                  <button
                    onClick={{() => handleDelete(item.id)}}
                    className="text-red-600 hover:underline"
                  >
                    Delete
                  </button>
                </td>
              </tr>
            ))}}
          </tbody>
        </table>
      </div>
    </div>
  );
}}
'''


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/generate_resource.py ResourceName")
        print("Example: python scripts/generate_resource.py Product")
        sys.exit(1)

    resource_name = sys.argv[1]
    snake_name = to_snake_case(resource_name)

    print(f"🚀 Generating resource: {resource_name}")

    # Get project root
    script_dir = Path(__file__).parent
    backend_dir = script_dir.parent
    project_dir = backend_dir.parent

    # Generate backend files
    model_path = backend_dir / "app" / "models" / f"{snake_name}.py"
    schema_path = backend_dir / "app" / "schemas" / f"{snake_name}.py"
    router_path = backend_dir / "app" / "routers" / f"{snake_name}s.py"

    model_path.write_text(generate_model(resource_name, snake_name))
    print(f"✓ Created {model_path}")

    schema_path.write_text(generate_schema(resource_name))
    print(f"✓ Created {schema_path}")

    router_path.write_text(generate_router(resource_name, snake_name))
    print(f"✓ Created {router_path}")

    # Generate frontend files
    frontend_dir = project_dir / "frontend" / "src" / "pages"
    if frontend_dir.exists():
        list_page = frontend_dir / f"{resource_name}List.tsx"
        list_page.write_text(generate_frontend_list(resource_name))
        print(f"✓ Created {list_page}")

    print(f"\n✅ Resource '{resource_name}' generated successfully!")
    print(f"\nNext steps:")
    print(f"1. Add router to app/main.py:")
    print(f"   from app.routers import {snake_name}s")
    print(f"   app.include_router({snake_name}s.router, prefix=settings.API_V1_STR)")
    print(f"2. Update app/models/__init__.py")
    print(f"3. Update app/schemas/__init__.py")
    print(f"4. Restart the backend server")
    print(f"5. Add routes to frontend App.tsx")


if __name__ == "__main__":
    main()
